Unit test bugfixes
rmotr-group-projects/pyp-w3-gw-decorators-library pull request #50
Opened 2017-06-16 16:33 UTC by jsymons

- Changed timeout unit test so that it requires the exception to raise before the wrapped function's execution is finished. (Before students could just compare the time before execution and after, and if it was longer than the timeout raise the exception)
- Changed memoize unit test so that it requires that if the parameters are in the cache that they return the value from the cache. (Before the tests would pass if they merely ran the function and stored the result in the cache, without ever checking if it was already there)

2017-06-16 18:45 UTC, santiagobasulto requested changes
I'd use mock, let's see what @martinzugnoni says.

2017-06-16 18:45 UTC, santiagobasulto commented on tests/test_decorators.py
> +    		return a + b
I see over indentation here, maybe tabs?

![image](https://user-images.githubusercontent.com/872296/27240301-8eb2a48e-52aa-11e7-8d77-b5800bb7d362.png)

2017-06-16 18:45 UTC, santiagobasulto commented on tests/test_decorators.py
> +    	self.assertTrue(after - before < 3, "Not using cached value.")
Looking again at it, I don't think it's a good idea to slow down the tests to check for a given condition. This is why `mock` is used for. @martinzugnoni, what do you think?

2017-06-16 18:58 UTC, jsymons commented on tests/test_decorators.py
> +    	self.assertTrue(after - before < 3, "Not using cached value.")
Yeah you're right, there's better ways to do this, I'll re-write the memoize stuff later tonight.

2017-06-17 00:31 UTC, jsymons commented
Revised memoize test to use `mock.patch`

2017-06-17 00:32 UTC, jsymons commented on tests/test_decorators.py
> +    		return a + b
Identation issue removed in new commit.

2017-08-01 18:36 UTC, santiagobasulto approved these changes

2017-08-02 23:49 UTC, closed without merging